language: go
# cannot install golint for go version 1.8.x and lower
go:
  - 1.9.x
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
os:
  - linux
  - osx
  - windows
before_script:
  - go get -v github.com/sirupsen/logrus
  - go get -v github.com/stretchr/testify
  - go get -v github.com/konsorten/go-windows-terminal-sequences
script:
  - go test ./...
